CREATE TABLE investments (
    id UUID PRIMARY KEY,
    isa_id UUID REFERENCES isas(id) ON DELETE SET NULL,
    fund_id UUID REFERENCES funds(id) ON DELETE SET NULL,
    amount DECIMAL(15,2) NOT NULL,
    invested_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);